$global:win11ProbeErrors=New-Object System.Collections.Generic.List[object]
function Probe($name,[scriptblock]$fn){try { & $fn }catch { $global:win11ProbeErrors.Add([pscustomobject]@{Probe=$name;Error=$_.Exception.Message}); $null }}
$id=[Security.Principal.WindowsIdentity]::GetCurrent();$principal=New-Object Security.Principal.WindowsPrincipal($id)
$policy='HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate'
$r=[ordered]@{Time=(Get-Date -Format o);Account=$id.Name;Elevated=$principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator);Groups=@($id.Groups | ForEach-Object {try {$_.Translate([Security.Principal.NTAccount]).Value}catch {$_.Value}});Policy=Probe Policy {Get-ItemProperty $policy -ErrorAction Stop | Select-Object TargetReleaseVersion,TargetReleaseVersionInfo,ProductVersion,TargetReleaseProductVersion,UseWUServer,DisableOSUpgrade,DisableWindowsUpdateAccess};PolicyACL=Probe ACL {(Get-Acl $policy -ErrorAction Stop).Access | Select-Object IdentityReference,RegistryRights,AccessControlType};Appraiser=Probe Appraiser {Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\TargetVersionUpgradeExperienceIndicators' -ErrorAction Stop | ForEach-Object {Get-ItemProperty $_.PSPath | Select-Object PSChildName,UpgEx,UpgExU,RedReason,GatedBlockId,FailedPrereqs,Timestamp,DataExpDate}};SecureBootRegistry=Probe SecureBootRegistry {Get-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\SecureBoot\State' -ErrorAction Stop | Select-Object UEFISecureBootEnabled};SecureBootCmdlet=Probe SecureBoot {Confirm-SecureBootUEFI -ErrorAction Stop};TPM=Probe TPM {Get-Tpm -ErrorAction Stop | Select-Object TpmPresent,TpmReady,TpmEnabled,TpmActivated,ManufacturerIdTxt,ManufacturerVersion};TPMWMI=Probe TPMWMI {Get-CimInstance -Namespace root\cimv2\security\microsofttpm -ClassName Win32_Tpm -ErrorAction Stop | Select-Object SpecVersion,IsActivated_InitialValue,IsEnabled_InitialValue,IsOwned_InitialValue};Disks=Probe Disk {Get-Disk -ErrorAction Stop | Select-Object Number,PartitionStyle,Size};TPMDevice=Probe TPMDevice {Get-PnpDevice -Class SecurityDevices -ErrorAction Stop | Select-Object FriendlyName,Status};SecurityServices=Probe Services {Get-CimInstance Win32_Service -ErrorAction Stop | Where-Object {$_.Name -match 'avp|klnagent|LdTerm|ProcessCtr|CommonService|WinDefend'} | Select-Object Name,State,StartMode};SecurityDrivers=Probe Drivers {Get-CimInstance Win32_SystemDriver -ErrorAction Stop | Where-Object {$_.Name -match 'LdMFilter|KLIF|klflt|Ldcore|ldwfp'} | Select-Object Name,State,StartMode};ExistingSetup=Probe Media {Get-ChildItem -LiteralPath 'C:\软件安装包' -Recurse -File -ErrorAction Stop | Where-Object {$_.Extension -in '.iso','.img' -or $_.Name -eq 'setup.exe'} | Select-Object FullName,Length}}
$r.Errors=@($global:win11ProbeErrors.ToArray())
$r | ConvertTo-Json -Depth 7 | Set-Content -Encoding UTF8 reports\2026-10-05\Win11只读资格复测.json
$r | ConvertTo-Json -Depth 7

