args <- commandArgs(trailingOnly=TRUE)
stopifnot(length(args) == 1L, file.exists(args[1]))
ip <- installed.packages()
write.csv(ip[, c('Package', 'Version', 'Built', 'LibPath')], 'r-package-snapshot.csv', row.names=FALSE)
required <- c('data.table','duckdb','DBI','xgboost','rugarch','tidymodels','reticulate','targets','renv','grf')
stopifnot(length(setdiff(required, ip[, 'Package'])) == 0L)
library(data.table)
setDTthreads(6)
dt <- data.table(g=rep(c('a','b'), each=50000), v=1:100000)
stopifnot(sum(dt[, .(s=sum(as.numeric(v))), by=g]$s) == 5000050000)
con <- DBI::dbConnect(duckdb::duckdb(), config=list(threads='6', memory_limit='2GB'))
duckdb::duckdb_register(con, 'sample', dt)
DBI::dbExecute(con, "COPY sample TO 'r-check.parquet' (FORMAT PARQUET)")
stopifnot(DBI::dbGetQuery(con, "SELECT COUNT(*) n FROM read_parquet('r-check.parquet')")$n == 100000)
DBI::dbDisconnect(con, shutdown=TRUE)
set.seed(1)
x <- matrix(rnorm(20000*20),20000,20)
y <- as.integer(x %*% rnorm(20) + rnorm(20000) > 0)
dm <- xgboost::xgb.DMatrix(x,label=y,nthread=6)
m <- xgboost::xgb.train(params=list(objective='binary:logistic',tree_method='hist',nthread=6,seed=1),
                        data=dm,nrounds=60,verbose=0)
accuracy <- mean((predict(m,dm) > .5) == y)
stopifnot(accuracy > .9)
Sys.setenv(RETICULATE_PYTHON=args[1])
pl <- reticulate::import('polars')
pa <- reticulate::import('pyarrow.parquet')
stopifnot(pa$read_table('r-check.parquet')$num_rows == 100000)
result <- list(status='passed', package_count=nrow(ip), xgboost_accuracy=accuracy,
               checks=c('10-key-packages','data.table','R-duckdb-parquet','R-xgboost','reticulate-pyarrow'))
jsonlite::write_json(result,'r-result.json',auto_unbox=TRUE,pretty=TRUE)
cat(jsonlite::toJSON(result,auto_unbox=TRUE), '\n')
